### ISSUE TITLE
Gimp ask for format options for every layer when exporting.

### ISSUE THREAD

**Issue by KevanAwesome** [kamilburda/gimp-export-layers#103] opened 2023-06-05 15:21 UTC
When exporting the layers gimp keeps asking for the format options[save options] for every layer.
Is that suppose to happen?

I was using 3.3.1 before and it used to only ask once, but it kept crashing[back-\foreground thing] so I updated.

So I'm not sure if that's a new thing.

**Comment by SirYaro** [comment] 2023-06-05 16:37
Same here (version 3.3.5)

**Comment by kamilburda** [comment] 2023-06-05 17:36
This is definitely not meant to happen. There are [a few (seldom used) file formats where the prompt is displayed for each layer](https://kamilburda.github.io/gimp-export-layers/sections/Known-Issues.html) - this is a limitation of the file format plug-ins.

I am unable to reproduce this on my end. Can you provide the following information so I could track down the problem?
* File format you use for export
* Your GIMP version
* Your operating system
* Procedures and constraints used (in the plug-in dialog, click on Settings -> Show More Settings to display them)

**Comment by SirYaro** [comment] 2023-06-05 22:15
In my case:

-     Version of Export Layers: 3.3.5
-     File format you use for export: png
-     GIMP version:  2.10.32
-     operating system:  Linux (neon 20.04)
-     Procedures and constraints used (in the plug-in dialog, click on Settings -> Show More Settings to display them): 
proc: insert fg layers, insert bg layers
const: inc layers, only top-lvl layers, inc layers groups

**Comment by KevanAwesome** [comment] 2023-06-06 02:39
Plugin Version: 3.3.5
File Format: PNG and JPG [Tested both]
GIMP Version: 2.10.34
Operating system: Windows 10

Procedures:
> - Ignore Folder Structure
> - Insert Foreground Layers

Constraints:
> - Include layer groups
> - Only layers without tags

Folder Structure:

> Layer Group [Foreground Tagged]
> 
>

**Comment by kamilburda** [comment] 2023-06-06 17:45
Thank you both. It appears that checking `Include layer groups` or having no `Include ...` constraint active causes this behavior. I'll try to fix this and make a new release.

**Comment by kamilburda** [comment] 2023-06-06 19:09
Fixed in 3.3.6.

**Closed by kamilburda** 2023-06-06 19:09 UTC
